"""
You are given two strings, str_1 and str_2, where str_2 is generated by randomly shuffling str_1 and then adding one letter at a random position.
Write a function that returns the letter that was added to str_2.

Examples:
csFindAddedLetter(str_1 = "bcde", str_2 = "bcdef") -> "f"
csFindAddedLetter(str_1 = "", str_2 = "z") -> "z"
csFindAddedLetter(str_1 = "b", str_2 = "bb") -> "b"
csFindAddedLetter(str_1 = "bf", str_2 = "bfb") -> "b"

Notes:
str_1 and str_2 both consist of only lowercase alpha characters.
[execution time limit] 4 seconds (py3)

[input] string str_1

[input] string str_2

[output] string
"""

def csFindAddedLetter(str_1, str_2): 
    # create two empty strings to hold the strings that are passed in
    small_str = ""
    large_str = ""
    
    # if the length of string 1 is greater than the length of string 2
    if len(str_1) > len(str_2):
        # assign the small string to string 2
        small_str = str_2
        # assign the larger string to string 1
        large_str = str_1
        
    else:  # if the length of string 2 is greater than the length of string 1
        # assign the small string to string 1
        small_str = str_1
        # assign the large string to string 2
        large_str = str_2
        
    # keep a running total to add to for sum of character chodes
    small_total = 0
    large_total = 0
    i = 0 
    
    # when the index is less than the small string -- add the character codes to both strings    and increment the index
    while (i < len(small_str)):
        small_total += ord(small_str[i])
        large_total += ord(large_str[i])
        i += 1
    
    # add the last character code to the larger string
    large_total += ord(large_str[i])
    
    # subtract the small character code total from the large character code total for the        character code of the character that is different between the two strings
    res = large_total - small_total
    
    # turn the character code into a character and return
    return chr(res)

print(csFindAddedLetter(str_1 = "bcde", str_2 = "bcdef"))
print(csFindAddedLetter(str_1 = "", str_2 = "z"))
print(csFindAddedLetter(str_1 = "b", str_2 = "bb"))
print(csFindAddedLetter(str_1 = "bf", str_2 = "bfb"))

# def csFindAddedLetter(str_1, str_2):
    # create a dictionary to store the values we map through
    # values = {}
    
    # for i in str_2:
    #     if i in values:
    #         values[i] += 1
    #     else:
    #         values[i] = 1
    
    # for i in str_1:
    #     values[i] -= 1
    
    # for character in values:
    #     if values[character] == 1:
    #         return character